travis:
  secure:
    BINSTAR_TOKEN: aYOo5DLaly7FtY07vFOZcTD80ET74YJOB2+czAeqI7iiRXoTebKe5YszW0lph5h7rM6SZUOW2dYVT5KF18novWz4GMn+dYPf0HtrmhjumCd5R5M49M+pBdFIM0SLcXHJ/32N5Q4qKQXpsB/fSE9LNsIbwnypB635+aFMlL1iMWOcwA/RUQGond0suvCj/hWSLe+5Ykv5YtneJPlwf9peVpyEj2S1145Tmc3LU+6AkUAovFhT0AdwZkQgUqz81bVdR3x9HliGj9CkOVVhbI1aoexczLW7k8hcyzoisIyRjL8hCOLp4vBcAQYL3dXiq5XR62LRIrEsB2pLMBrmFyqJeSVp3EyJs9gdeFDeI1XDl6eVXExX3mi3pf0sDDQw7eoLj+xH6DaFOLgfKMKqunaLwtB0cOaSf66zikTn1ecaWifkTj+uOYX3XqDD5WH9pIY1KVZVGe9CNNsu9b023tYxrIb5ABcEHf/Zpls3kqRMa+EJAqV5Xe9/4XoekCo+SNdtpeO/6LA4gTSq+E3ijyoEKEpwp1row8mUTUZaKV8dwzfc+CF8lJI/LxMaUUeGz2lFI7Hb3hzjU7qytLlPwCoclLQOLQsXqeUzxzE+iGI8myG/dKnieY7VgDpMZAEHL+aKF6pRGSMVYDqDM6fcJDJ2r/GeiyW8GYdBx6wqK5ANz4s=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
